### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by Kurren123** [Baransu/elm-docs#6]
Any plans to upgrade for elm 0.19?

**Comment by baransu** [comment]
I'll try to find time to upgrade it to 0.19. If you're willing to help any PR is welcome 🙂

**Comment by vViktorPL** [comment]
I've created a PR for that: #7 :)

**Comment by baransu** [comment]
Released as `0.4.0`. You can try it now! Thanks @vViktorPL
